  name: 'Deploy to AWS S3' # js action
  description: 'Deploy a website via AWS S3'
  inputs: 
      bucket:
          description: 'S3 bucket name'
          required: true
      bucket-region:
          description: 'region of bucket S3'
          required: false
          default: 'us-eats-1'
      dist-folder:
          description: 'folder containing deploy site'
          required: true
  runs:
    using: 'node16'
    main: 'main.js'